### PR TITLE
feat: support cursor editor

### PR DESCRIPTION
**Pull request by alanhe421**
Cursor is a fork of VS Code.

The URL scheme rules are the same.

### CODE REVIEW

**Comment by ohkimur** [comment]
@alanhe421 @ericclemmons This might be related to #82. Maybe there is a great benefit in merging #82 first and then adapting and merging this too.

**Comment by alanhe421** [comment]
This change is not significant. Personally, I think it's fine to merge it in first, but waiting for #82 to be merged is also okay.

**Comment by alexgorbatchev** [comment]
I have published a fork which includes this PR https://github.com/alexgorbatchev/click-to-component-next

**Comment by ericclemmons** [comment]
I just did the same thing too.  `editor="cursor"` and it worked!

**Pull request merged**
